config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os-hub/demo-advanced:
      branch: main
      repo: https://github.com/ai4os-hub/demo-advanced
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ai4os-hub/demo-advanced git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cornflower-chihuahua.sh
        container: qc.acc_pasty-salmon-seahorse
  QC.Doc:
    repos:
      github.com/ai4os-hub/demo-advanced find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-brown-stoat.sh
        container: qc.doc_snappy-seashell-duck
      github.com/ai4os-hub/demo-advanced git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-denim-olm.sh
        container: qc.doc_flabby-orchid-fox
  QC.Lic:
    repos:
      github.com/ai4os-hub/demo-advanced licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ecru-booby.sh
        container: qc.lic_scummy-wheat-mongrel
  QC.Ver:
    repos:
      github.com/ai4os-hub/demo-advanced get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-tan-squirrel.sh
        container: qc.ver_tacky-russet-goat
timeout: 5400
